name: smoke-macos-bigsur

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

env:
    PERL_SKIP_TTY_TEST: 1

jobs:
  perl:

    runs-on: macos-11.0

    steps:
      - uses: actions/checkout@master
        with:
            fetch-depth: 10
      - name: Configure
        run: |
            export SDK=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk
            perl Makefile.PL
      - name: Build
        run: |
            make
      - name: Run Tests
        run: |
            make test
            make disttest NOECHO=
